version: '3.4'

services:
  # Base de dados MySQL.
  db:
    image: mysql:8
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./initialize_database:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${GEN_DB_ROOT}
      MYSQL_DATABASE: ${GEN_DB_SCHEMA}
      MYSQL_PASSWORD: ${GEN_DB_PASS}
    ports:
      - "${GEN_DB_PORT}:3306"
    networks:
      - desafio
  
  # Sistema que auxilia na administração da Base de dados do MySQL.
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: localhost
      PMA_PORT: db
    ports:
      - "8085:80"
    depends_on:
      - db
    networks:
      - desafio

  # Serviço do projeto ASP.Net Core 7 - Minimal API
  desafiodev.webapi:    
    build:
      context: .
      dockerfile: src/DesafioDev.WebApi/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - desafio

  # Serviço do FrontEnd -Angular
  angular-app:
    build: 
      context: .
      dockerfile: front-end/Dockerfile
    ports:
      - "8080:80"
    networks:
      - desafio

networks:
  desafio:

volumes:
  db: