version: '3.4'

services:
  # Base de dados MySQL.
  db:
    image: mysql:8
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${GEN_DB_ROOT}
      MYSQL_DATABASE: ${GEN_DB_SCHEMA}
      MYSQL_PASSWORD: ${GEN_DB_PASS}
    ports:
      - "${GEN_DB_PORT}:3306"
    networks:
      - desafio
  
  # Sistema que auxilia na administração da Base de dados do MySQL.
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: localhost
      PMA_PORT: ${GEN_DB_PORT}
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - desafio

  # Serviço do FrontEnd -Angular
  # angular-app:
  #   build: ./front-end
  #   ports:
  #     - "${HOST_APP_FRONTEND_PORT}:80"
  #   depends_on:
  #     - api-service
  #   networks:
  #     - desafio


  # Serviço do projeto ASP.Net Core 7 - Minimal API
  desafiodev.webapi:
    image: ${DOCKER_REGISTRY-}desafiodevwebapi
    build:
      context: .
      dockerfile: src/DesafioDev.WebApi/Dockerfile
    depends_on:
      - db
    networks:
      - desafio

networks:
  desafio:

volumes:
  db: